"""
Catalogue Niche Engine — Concept Factory Silver Economy
20 niches × 6 pays (FR, DE, CH, BE+LU, UK, NL).
Les métriques (volume, CPC, KD, CPA cible) sont des estimations qualifiées
à recalibrer via DataForSEO une fois la clé fournie.

La source principale reste /app/frontend/public/docs/niche-study.md.
"""

from datetime import datetime, timezone
from typing import List


COUNTRIES = [
    {"code": "FR", "name": "France", "flag": "🇫🇷", "currency": "EUR"},
    {"code": "DE", "name": "Allemagne", "flag": "🇩🇪", "currency": "EUR"},
    {"code": "CH", "name": "Suisse", "flag": "🇨🇭", "currency": "CHF"},
    {"code": "BE", "name": "Belgique+Lux", "flag": "🇧🇪", "currency": "EUR"},
    {"code": "UK", "name": "Royaume-Uni", "flag": "🇬🇧", "currency": "GBP"},
    {"code": "NL", "name": "Pays-Bas", "flag": "🇳🇱", "currency": "EUR"},
]


NICHES: List[dict] = [
    {
        "slug": "enfile-bas-contention",
        "rank": 1,
        "emoji": "🪡",
        "name": "Enfile-bas de contention",
        "category": "Aide au quotidien",
        "tagline": "Enfilez vos bas de contention en 10 secondes, sans vous baisser.",
        "description": "Produit permettant d'enfiler bas/chaussettes de contention seul, sans se pencher. Produit problème-solution ultra clair.",
        "keywords": ["enfile-bas", "anziehhilfe strümpfe", "sock aid", "enfile-chaussettes"],
        "buy_price_eur": [3, 5],
        "sell_price_eur": [29, 39],
        "aov_eur": [29, 39],
        "margin_pct": 82,
        "ecf_score": 88,
        "best_country": "FR",
        "hero": False,
        "suppliers": ["CJ Dropshipping (EU warehouse)", "BigBuy ES", "AliExpress (CE)"],
        "country_metrics": {
            "FR": {"volume": 2900, "cpc": 0.45, "kd": 24, "cpa_target": 12, "seasonality": "Stable"},
            "DE": {"volume": 4800, "cpc": 0.55, "kd": 28, "cpa_target": 14, "seasonality": "Stable"},
            "CH": {"volume": 390,  "cpc": 0.60, "kd": 22, "cpa_target": 15, "seasonality": "Stable"},
            "BE": {"volume": 480,  "cpc": 0.50, "kd": 20, "cpa_target": 12, "seasonality": "Stable"},
            "UK": {"volume": 3600, "cpc": 0.42, "kd": 30, "cpa_target": 11, "seasonality": "Stable"},
            "NL": {"volume": 720,  "cpc": 0.48, "kd": 22, "cpa_target": 13, "seasonality": "Stable"},
        },
    },
    {
        "slug": "pince-prehension",
        "rank": 2,
        "emoji": "🎣",
        "name": "Pince de préhension télescopique",
        "category": "Aide au quotidien",
        "tagline": "Ne vous baissez plus jamais. Ramassez tout en un geste.",
        "description": "Attrape-objets pliable pour ramasser sans se baisser. Fort potentiel gift pour aidants.",
        "keywords": ["pince de préhension", "greifhilfe", "reacher grabber", "pince à attraper"],
        "buy_price_eur": [5, 8],
        "sell_price_eur": [29, 44],
        "aov_eur": [29, 44],
        "margin_pct": 80,
        "ecf_score": 85,
        "best_country": "FR",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 3600, "cpc": 0.60, "kd": 26, "cpa_target": 15, "seasonality": "Pic Décembre (cadeau)"},
            "DE": {"volume": 5400, "cpc": 0.70, "kd": 30, "cpa_target": 16, "seasonality": "Pic Décembre"},
            "CH": {"volume": 480,  "cpc": 0.80, "kd": 25, "cpa_target": 18, "seasonality": "Stable"},
            "BE": {"volume": 590,  "cpc": 0.65, "kd": 22, "cpa_target": 14, "seasonality": "Stable"},
            "UK": {"volume": 8100, "cpc": 0.55, "kd": 34, "cpa_target": 13, "seasonality": "Pic Décembre"},
            "NL": {"volume": 890,  "cpc": 0.60, "kd": 24, "cpa_target": 14, "seasonality": "Stable"},
        },
    },
    {
        "slug": "pilulier-electronique",
        "rank": 3,
        "emoji": "💊",
        "name": "Pilulier électronique hebdomadaire",
        "category": "Santé & bien-être",
        "tagline": "Ne manquez plus jamais un traitement. Alertes programmables 7j/7.",
        "description": "Pilulier connecté/sonore avec alarmes pour ne jamais oublier un traitement. Marché haut potentiel en DE/NL.",
        "keywords": ["pilulier électronique", "elektronische tablettenbox", "electronic pill dispenser"],
        "buy_price_eur": [12, 16],
        "sell_price_eur": [39, 59],
        "aov_eur": [39, 59],
        "margin_pct": 74,
        "ecf_score": 82,
        "best_country": "DE",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 1900, "cpc": 0.90, "kd": 32, "cpa_target": 22, "seasonality": "Stable"},
            "DE": {"volume": 4400, "cpc": 1.10, "kd": 38, "cpa_target": 25, "seasonality": "Stable"},
            "CH": {"volume": 320,  "cpc": 1.30, "kd": 28, "cpa_target": 27, "seasonality": "Stable"},
            "BE": {"volume": 260,  "cpc": 0.95, "kd": 26, "cpa_target": 22, "seasonality": "Stable"},
            "UK": {"volume": 5400, "cpc": 0.80, "kd": 40, "cpa_target": 20, "seasonality": "Stable"},
            "NL": {"volume": 880,  "cpc": 1.00, "kd": 30, "cpa_target": 23, "seasonality": "Stable"},
        },
    },
    {
        "slug": "chauffe-pieds-senior",
        "rank": 4,
        "emoji": "🔥",
        "name": "Chauffe-pieds électrique senior",
        "category": "Confort & chaleur",
        "tagline": "Adieu les pieds glacés. Chaleur douce en 30 secondes.",
        "description": "Coussin chauffant pieds/jambes avec télécommande filaire. Pic automne/hiver fort. Excellent UGC.",
        "keywords": ["chauffe-pieds", "fußwärmer elektrisch", "electric foot warmer"],
        "buy_price_eur": [14, 18],
        "sell_price_eur": [49, 69],
        "aov_eur": [49, 69],
        "margin_pct": 76,
        "ecf_score": 84,
        "best_country": "DE",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 2900, "cpc": 0.70, "kd": 30, "cpa_target": 20, "seasonality": "Pic Oct–Fév"},
            "DE": {"volume": 6600, "cpc": 0.85, "kd": 36, "cpa_target": 22, "seasonality": "Pic Oct–Fév"},
            "CH": {"volume": 480,  "cpc": 0.95, "kd": 28, "cpa_target": 24, "seasonality": "Pic Oct–Fév"},
            "BE": {"volume": 720,  "cpc": 0.75, "kd": 26, "cpa_target": 21, "seasonality": "Pic Oct–Fév"},
            "UK": {"volume": 4400, "cpc": 0.65, "kd": 32, "cpa_target": 19, "seasonality": "Pic Oct–Fév"},
            "NL": {"volume": 1300, "cpc": 0.80, "kd": 28, "cpa_target": 22, "seasonality": "Pic Oct–Fév"},
        },
    },
    {
        "slug": "loupe-eclairante-led",
        "rank": 5,
        "emoji": "🔍",
        "name": "Loupe éclairante LED",
        "category": "Vision & lecture",
        "tagline": "Lire le journal sans effort. Lumière douce + grossissement 5×.",
        "description": "Loupe grossissante avec éclairage LED intégré pour lecture/travaux manuels.",
        "keywords": ["loupe éclairante", "leuchtlupe", "lighted magnifier", "loupe LED"],
        "buy_price_eur": [7, 10],
        "sell_price_eur": [34, 49],
        "aov_eur": [34, 49],
        "margin_pct": 78,
        "ecf_score": 86,
        "best_country": "FR",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 2900, "cpc": 0.55, "kd": 22, "cpa_target": 15, "seasonality": "Stable"},
            "DE": {"volume": 3600, "cpc": 0.65, "kd": 26, "cpa_target": 17, "seasonality": "Stable"},
            "CH": {"volume": 390,  "cpc": 0.75, "kd": 22, "cpa_target": 19, "seasonality": "Stable"},
            "BE": {"volume": 390,  "cpc": 0.60, "kd": 20, "cpa_target": 15, "seasonality": "Stable"},
            "UK": {"volume": 6600, "cpc": 0.50, "kd": 28, "cpa_target": 14, "seasonality": "Stable"},
            "NL": {"volume": 720,  "cpc": 0.58, "kd": 22, "cpa_target": 15, "seasonality": "Stable"},
        },
    },
    {
        "slug": "veilleuse-detection-mouvement",
        "rank": 6,
        "emoji": "💡",
        "name": "Veilleuse détection mouvement",
        "category": "Sécurité maison",
        "tagline": "Sécurisez le chemin de nuit. 3 veilleuses autonomes, zéro installation.",
        "description": "Pack de 3-6 veilleuses LED sans fil avec détection de mouvement, installation sans câble. Anti-chute de nuit.",
        "keywords": ["veilleuse détection mouvement", "nachtlicht bewegungsmelder", "motion sensor night light"],
        "buy_price_eur": [7, 12],
        "sell_price_eur": [29, 44],
        "aov_eur": [29, 44],
        "margin_pct": 78,
        "ecf_score": 80,
        "best_country": "NL",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 880,  "cpc": 0.40, "kd": 20, "cpa_target": 12, "seasonality": "Pic Automne"},
            "DE": {"volume": 2400, "cpc": 0.55, "kd": 26, "cpa_target": 15, "seasonality": "Pic Automne"},
            "CH": {"volume": 320,  "cpc": 0.65, "kd": 22, "cpa_target": 18, "seasonality": "Stable"},
            "BE": {"volume": 390,  "cpc": 0.45, "kd": 20, "cpa_target": 13, "seasonality": "Stable"},
            "UK": {"volume": 3600, "cpc": 0.38, "kd": 28, "cpa_target": 11, "seasonality": "Pic Automne"},
            "NL": {"volume": 2400, "cpc": 0.48, "kd": 24, "cpa_target": 14, "seasonality": "Pic Automne"},
        },
    },
    {
        "slug": "reveil-senior-parlant",
        "rank": 7,
        "emoji": "⏰",
        "name": "Réveil senior grands chiffres parlant",
        "category": "Quotidien",
        "tagline": "Savoir l'heure et la date d'un simple geste. Grande visibilité + annonce vocale.",
        "description": "Réveil parlant avec date/heure audibles + grands chiffres + alarme médicaments.",
        "keywords": ["réveil parlant senior", "sprechender wecker", "talking clock seniors"],
        "buy_price_eur": [11, 16],
        "sell_price_eur": [39, 59],
        "aov_eur": [39, 59],
        "margin_pct": 77,
        "ecf_score": 78,
        "best_country": "UK",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 1000, "cpc": 0.65, "kd": 24, "cpa_target": 18, "seasonality": "Pic Décembre"},
            "DE": {"volume": 2400, "cpc": 0.80, "kd": 30, "cpa_target": 20, "seasonality": "Pic Décembre"},
            "CH": {"volume": 210,  "cpc": 0.90, "kd": 25, "cpa_target": 22, "seasonality": "Stable"},
            "BE": {"volume": 210,  "cpc": 0.70, "kd": 22, "cpa_target": 18, "seasonality": "Stable"},
            "UK": {"volume": 3600, "cpc": 0.60, "kd": 28, "cpa_target": 16, "seasonality": "Pic Décembre"},
            "NL": {"volume": 720,  "cpc": 0.72, "kd": 24, "cpa_target": 18, "seasonality": "Stable"},
        },
    },
    {
        "slug": "canne-pliante-premium",
        "rank": 8,
        "emoji": "🚶",
        "name": "Canne pliante légère premium",
        "category": "Mobilité",
        "tagline": "La canne qui se glisse dans votre sac. 279g, pliable, élégante.",
        "description": "Canne ultra-légère aluminium, pliable 4 sections, esthétique (couleurs tissus), bout antichoc.",
        "keywords": ["canne pliante", "faltbarer gehstock", "folding walking cane"],
        "buy_price_eur": [13, 18],
        "sell_price_eur": [49, 79],
        "aov_eur": [49, 79],
        "margin_pct": 78,
        "ecf_score": 91,
        "best_country": "FR",
        "hero": True,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 5400, "cpc": 0.85, "kd": 34, "cpa_target": 24, "seasonality": "Stable"},
            "DE": {"volume": 8100, "cpc": 1.10, "kd": 42, "cpa_target": 28, "seasonality": "Stable"},
            "CH": {"volume": 590,  "cpc": 1.30, "kd": 32, "cpa_target": 30, "seasonality": "Stable"},
            "BE": {"volume": 890,  "cpc": 0.95, "kd": 30, "cpa_target": 25, "seasonality": "Stable"},
            "UK": {"volume": 6600, "cpc": 0.80, "kd": 38, "cpa_target": 22, "seasonality": "Stable"},
            "NL": {"volume": 1600, "cpc": 0.95, "kd": 30, "cpa_target": 25, "seasonality": "Stable"},
        },
    },
    {
        "slug": "canne-siege-pliante",
        "rank": 9,
        "emoji": "🪑",
        "name": "Canne-siège pliante",
        "category": "Mobilité",
        "tagline": "Quand vous marchez, c'est une canne. Quand vous fatiguez, c'est un siège.",
        "description": "Canne qui se transforme en siège d'appoint. Parfait pour promenades, marchés, attentes.",
        "keywords": ["canne siège", "sitzstock", "walking stick seat"],
        "buy_price_eur": [22, 30],
        "sell_price_eur": [79, 119],
        "aov_eur": [79, 119],
        "margin_pct": 75,
        "ecf_score": 84,
        "best_country": "UK",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 3600, "cpc": 0.55, "kd": 28, "cpa_target": 22, "seasonality": "Pic Printemps"},
            "DE": {"volume": 2900, "cpc": 0.70, "kd": 32, "cpa_target": 26, "seasonality": "Pic Printemps"},
            "CH": {"volume": 260,  "cpc": 0.85, "kd": 24, "cpa_target": 28, "seasonality": "Stable"},
            "BE": {"volume": 390,  "cpc": 0.60, "kd": 22, "cpa_target": 22, "seasonality": "Stable"},
            "UK": {"volume": 5400, "cpc": 0.50, "kd": 32, "cpa_target": 20, "seasonality": "Pic Printemps"},
            "NL": {"volume": 720,  "cpc": 0.62, "kd": 26, "cpa_target": 23, "seasonality": "Stable"},
        },
    },
    {
        "slug": "rehausseur-wc",
        "rank": 10,
        "emoji": "🚽",
        "name": "Rehausseur WC avec accoudoirs",
        "category": "Salle de bain",
        "tagline": "Reprenez confiance dans votre salle de bain. Installation 5 min, sans outils.",
        "description": "Rehausseur 10 cm avec accoudoirs ergonomiques, installation sans outils.",
        "keywords": ["rehausseur wc", "toilettensitzerhöhung", "raised toilet seat"],
        "buy_price_eur": [19, 27],
        "sell_price_eur": [69, 99],
        "aov_eur": [69, 99],
        "margin_pct": 76,
        "ecf_score": 83,
        "best_country": "DE",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 4400, "cpc": 0.95, "kd": 36, "cpa_target": 28, "seasonality": "Stable"},
            "DE": {"volume": 9900, "cpc": 1.20, "kd": 44, "cpa_target": 32, "seasonality": "Stable"},
            "CH": {"volume": 590,  "cpc": 1.40, "kd": 34, "cpa_target": 35, "seasonality": "Stable"},
            "BE": {"volume": 880,  "cpc": 1.05, "kd": 32, "cpa_target": 28, "seasonality": "Stable"},
            "UK": {"volume": 6600, "cpc": 0.85, "kd": 38, "cpa_target": 25, "seasonality": "Stable"},
            "NL": {"volume": 1900, "cpc": 1.00, "kd": 34, "cpa_target": 28, "seasonality": "Stable"},
        },
    },
    {
        "slug": "barre-appui-baignoire",
        "rank": 11,
        "emoji": "🛁",
        "name": "Barre d'appui baignoire ventouse",
        "category": "Salle de bain",
        "tagline": "Sécurisez votre baignoire en 2 minutes. Aucun perçage, sécurité testée 100 kg.",
        "description": "Barre d'appui sans perçage, fixation ventouses puissantes, indicateurs sécurité.",
        "keywords": ["barre d'appui baignoire", "haltegriff badewanne", "bath grab bar"],
        "buy_price_eur": [12, 17],
        "sell_price_eur": [39, 59],
        "aov_eur": [39, 59],
        "margin_pct": 77,
        "ecf_score": 81,
        "best_country": "FR",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 2400, "cpc": 0.70, "kd": 28, "cpa_target": 22, "seasonality": "Stable"},
            "DE": {"volume": 3600, "cpc": 0.85, "kd": 32, "cpa_target": 26, "seasonality": "Stable"},
            "CH": {"volume": 260,  "cpc": 0.95, "kd": 26, "cpa_target": 28, "seasonality": "Stable"},
            "BE": {"volume": 390,  "cpc": 0.75, "kd": 24, "cpa_target": 22, "seasonality": "Stable"},
            "UK": {"volume": 4400, "cpc": 0.65, "kd": 32, "cpa_target": 20, "seasonality": "Stable"},
            "NL": {"volume": 590,  "cpc": 0.72, "kd": 26, "cpa_target": 22, "seasonality": "Stable"},
        },
    },
    {
        "slug": "coussin-voiture-ergonomique",
        "rank": 12,
        "emoji": "🚗",
        "name": "Coussin ergonomique assise voiture",
        "category": "Confort",
        "tagline": "Roulez des heures sans douleur. Gel haute densité + soutien lombaire.",
        "description": "Coussin gel/mousse mémoire de forme pour trajets longs + inclinaison corrective.",
        "keywords": ["coussin voiture ergonomique", "autositzkissen", "car seat cushion"],
        "buy_price_eur": [16, 22],
        "sell_price_eur": [49, 79],
        "aov_eur": [49, 79],
        "margin_pct": 76,
        "ecf_score": 83,
        "best_country": "DE",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 2100, "cpc": 0.80, "kd": 30, "cpa_target": 24, "seasonality": "Pic Été"},
            "DE": {"volume": 5400, "cpc": 1.00, "kd": 38, "cpa_target": 28, "seasonality": "Pic Été"},
            "CH": {"volume": 320,  "cpc": 1.15, "kd": 28, "cpa_target": 30, "seasonality": "Stable"},
            "BE": {"volume": 480,  "cpc": 0.85, "kd": 26, "cpa_target": 24, "seasonality": "Stable"},
            "UK": {"volume": 3600, "cpc": 0.72, "kd": 32, "cpa_target": 22, "seasonality": "Pic Été"},
            "NL": {"volume": 720,  "cpc": 0.82, "kd": 28, "cpa_target": 24, "seasonality": "Stable"},
        },
    },
    {
        "slug": "deambulateur-pliable-3-roues",
        "rank": 13,
        "emoji": "🦯",
        "name": "Déambulateur pliable 3 roues léger",
        "category": "Mobilité",
        "tagline": "Votre liberté retrouvée. Ultra-léger, pliable, se glisse dans le coffre.",
        "description": "Rollator ultra-compact pliable, frein, siège intégré, moins de 6 kg.",
        "keywords": ["déambulateur pliable", "rollator faltbar", "folding rollator"],
        "buy_price_eur": [55, 85],
        "sell_price_eur": [129, 199],
        "aov_eur": [129, 199],
        "margin_pct": 70,
        "ecf_score": 82,
        "best_country": "NL",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 3600,  "cpc": 1.30, "kd": 42, "cpa_target": 60,  "seasonality": "Stable"},
            "DE": {"volume": 14800, "cpc": 1.60, "kd": 50, "cpa_target": 72,  "seasonality": "Stable"},
            "CH": {"volume": 720,   "cpc": 1.80, "kd": 38, "cpa_target": 80,  "seasonality": "Stable"},
            "BE": {"volume": 880,   "cpc": 1.40, "kd": 36, "cpa_target": 60,  "seasonality": "Stable"},
            "UK": {"volume": 5400,  "cpc": 1.10, "kd": 44, "cpa_target": 52,  "seasonality": "Stable"},
            "NL": {"volume": 4400,  "cpc": 1.25, "kd": 40, "cpa_target": 58,  "seasonality": "Stable"},
        },
    },
    {
        "slug": "fauteuil-releveur-2-moteurs",
        "rank": 14,
        "emoji": "🛋",
        "name": "Fauteuil releveur électrique 2 moteurs",
        "category": "Confort premium",
        "tagline": "Se lever en douceur. S'installer sans douleur. Le fauteuil qui prend soin de vous.",
        "description": "Fauteuil relax 2 moteurs indépendants, couleurs tissu premium, livraison installation. HERO — 1 vente = 20-30 jours pub amortis.",
        "keywords": ["fauteuil releveur", "aufstehsessel", "lift chair recliner"],
        "buy_price_eur": [260, 420],
        "sell_price_eur": [799, 1490],
        "aov_eur": [799, 1490],
        "margin_pct": 72,
        "ecf_score": 79,
        "best_country": "FR",
        "hero": True,
        "suppliers": ["BigBuy", "Fournisseur EU dédié (sur demande)"],
        "country_metrics": {
            "FR": {"volume": 18100, "cpc": 2.50, "kd": 58, "cpa_target": 260, "seasonality": "Stable"},
            "DE": {"volume": 22200, "cpc": 2.80, "kd": 62, "cpa_target": 300, "seasonality": "Stable"},
            "CH": {"volume": 1300,  "cpc": 3.40, "kd": 52, "cpa_target": 380, "seasonality": "Stable"},
            "BE": {"volume": 2400,  "cpc": 2.70, "kd": 48, "cpa_target": 280, "seasonality": "Stable"},
            "UK": {"volume": 14800, "cpc": 2.20, "kd": 60, "cpa_target": 240, "seasonality": "Stable"},
            "NL": {"volume": 3600,  "cpc": 2.60, "kd": 50, "cpa_target": 260, "seasonality": "Stable"},
        },
    },
    {
        "slug": "lit-electrique-hauteur-variable",
        "rank": 15,
        "emoji": "🛏",
        "name": "Lit électrique senior hauteur variable",
        "category": "Confort premium",
        "tagline": "Le sommeil profond commence par le bon lit. Réglage sur-mesure en un bouton.",
        "description": "Lit 1 personne à hauteur variable + tête/pied relevables électriques. Confort, pas prescrit. HERO.",
        "keywords": ["lit électrique senior", "elektrisches pflegebett", "electric adjustable bed"],
        "buy_price_eur": [340, 540],
        "sell_price_eur": [990, 1790],
        "aov_eur": [990, 1790],
        "margin_pct": 70,
        "ecf_score": 76,
        "best_country": "DE",
        "hero": True,
        "suppliers": ["BigBuy", "Fournisseur EU dédié (sur demande)"],
        "country_metrics": {
            "FR": {"volume": 8100,  "cpc": 2.80, "kd": 60, "cpa_target": 340, "seasonality": "Stable"},
            "DE": {"volume": 18100, "cpc": 3.20, "kd": 66, "cpa_target": 400, "seasonality": "Stable"},
            "CH": {"volume": 880,   "cpc": 3.80, "kd": 56, "cpa_target": 480, "seasonality": "Stable"},
            "BE": {"volume": 1600,  "cpc": 2.95, "kd": 52, "cpa_target": 360, "seasonality": "Stable"},
            "UK": {"volume": 9900,  "cpc": 2.50, "kd": 62, "cpa_target": 300, "seasonality": "Stable"},
            "NL": {"volume": 2400,  "cpc": 2.85, "kd": 52, "cpa_target": 320, "seasonality": "Stable"},
        },
    },
    {
        "slug": "telephone-fixe-amplifie",
        "rank": 16,
        "emoji": "📞",
        "name": "Téléphone fixe amplifié grandes touches",
        "category": "Communication",
        "tagline": "Entendre ses proches à nouveau. Touches XXL, volume +40 dB, mémoires photo.",
        "description": "Téléphone fixe avec grosses touches + volume amplifié + numérotation rapide 8 touches photos.",
        "keywords": ["téléphone senior", "seniorentelefon", "amplified phone seniors"],
        "buy_price_eur": [18, 25],
        "sell_price_eur": [59, 89],
        "aov_eur": [59, 89],
        "margin_pct": 74,
        "ecf_score": 80,
        "best_country": "FR",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 4400, "cpc": 1.20, "kd": 38, "cpa_target": 28, "seasonality": "Pic Décembre"},
            "DE": {"volume": 6600, "cpc": 1.45, "kd": 44, "cpa_target": 32, "seasonality": "Pic Décembre"},
            "CH": {"volume": 480,  "cpc": 1.60, "kd": 34, "cpa_target": 35, "seasonality": "Stable"},
            "BE": {"volume": 720,  "cpc": 1.30, "kd": 32, "cpa_target": 28, "seasonality": "Stable"},
            "UK": {"volume": 5400, "cpc": 1.05, "kd": 40, "cpa_target": 25, "seasonality": "Stable"},
            "NL": {"volume": 1000, "cpc": 1.20, "kd": 32, "cpa_target": 27, "seasonality": "Stable"},
        },
    },
    {
        "slug": "monte-escalier-portable",
        "rank": 17,
        "emoji": "🪜",
        "name": "Monte-escalier portable (assistance)",
        "category": "Mobilité",
        "tagline": "Reprenez les escaliers sans épuisement. Assistance électrique discrète.",
        "description": "Assistance motorisée portable pour monter les escaliers en poussant, non-installé. Ultra-niche mais gros panier.",
        "keywords": ["monte escalier portable", "treppensteiger", "stair climber assist"],
        "buy_price_eur": [95, 160],
        "sell_price_eur": [299, 499],
        "aov_eur": [299, 499],
        "margin_pct": 68,
        "ecf_score": 74,
        "best_country": "CH",
        "hero": False,
        "suppliers": ["BigBuy", "CJ Dropshipping (stock limité)"],
        "country_metrics": {
            "FR": {"volume": 1300, "cpc": 2.10, "kd": 44, "cpa_target": 90,  "seasonality": "Stable"},
            "DE": {"volume": 2400, "cpc": 2.40, "kd": 50, "cpa_target": 110, "seasonality": "Stable"},
            "CH": {"volume": 590,  "cpc": 2.80, "kd": 38, "cpa_target": 140, "seasonality": "Stable (top marché)"},
            "BE": {"volume": 260,  "cpc": 2.20, "kd": 34, "cpa_target": 95,  "seasonality": "Stable"},
            "UK": {"volume": 1900, "cpc": 1.95, "kd": 46, "cpa_target": 85,  "seasonality": "Stable"},
            "NL": {"volume": 480,  "cpc": 2.15, "kd": 36, "cpa_target": 95,  "seasonality": "Stable"},
        },
    },
    {
        "slug": "couverture-chauffante-senior",
        "rank": 18,
        "emoji": "🔥",
        "name": "Couverture chauffante ergonomique",
        "category": "Confort & chaleur",
        "tagline": "La chaleur qui réveille les muscles. 9 niveaux, télécommande, lavable machine.",
        "description": "Couverture chauffante USB/secteur avec 9 niveaux chaleur + zones ciblées (nuque, dos, genoux).",
        "keywords": ["couverture chauffante", "heizdecke", "electric heated blanket"],
        "buy_price_eur": [16, 22],
        "sell_price_eur": [49, 79],
        "aov_eur": [49, 79],
        "margin_pct": 76,
        "ecf_score": 82,
        "best_country": "DE",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 3600, "cpc": 0.90, "kd": 32, "cpa_target": 22, "seasonality": "Pic Oct–Fév"},
            "DE": {"volume": 9900, "cpc": 1.10, "kd": 42, "cpa_target": 26, "seasonality": "Pic Oct–Fév"},
            "CH": {"volume": 720,  "cpc": 1.30, "kd": 34, "cpa_target": 28, "seasonality": "Pic Oct–Fév"},
            "BE": {"volume": 880,  "cpc": 0.95, "kd": 30, "cpa_target": 22, "seasonality": "Pic Oct–Fév"},
            "UK": {"volume": 8100, "cpc": 0.80, "kd": 38, "cpa_target": 20, "seasonality": "Pic Oct–Fév"},
            "NL": {"volume": 1900, "cpc": 0.95, "kd": 32, "cpa_target": 22, "seasonality": "Pic Oct–Fév"},
        },
    },
    {
        "slug": "lampe-luminotherapie",
        "rank": 19,
        "emoji": "☀️",
        "name": "Lampe luminothérapie compacte",
        "category": "Bien-être",
        "tagline": "Retrouvez votre énergie même en hiver. 30 min/jour suffisent.",
        "description": "Lampe 10 000 lux certifiée UV-free, format compact, anti-dépression saisonnière + énergie.",
        "keywords": ["luminothérapie", "tageslichtlampe", "light therapy lamp"],
        "buy_price_eur": [18, 26],
        "sell_price_eur": [69, 99],
        "aov_eur": [69, 99],
        "margin_pct": 75,
        "ecf_score": 85,
        "best_country": "NL",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 4400, "cpc": 1.20, "kd": 38, "cpa_target": 30, "seasonality": "Pic Oct–Mars"},
            "DE": {"volume": 9900, "cpc": 1.45, "kd": 46, "cpa_target": 34, "seasonality": "Pic Oct–Mars"},
            "CH": {"volume": 720,  "cpc": 1.70, "kd": 36, "cpa_target": 40, "seasonality": "Pic Oct–Mars"},
            "BE": {"volume": 1000, "cpc": 1.30, "kd": 34, "cpa_target": 32, "seasonality": "Pic Oct–Mars"},
            "UK": {"volume": 5400, "cpc": 1.05, "kd": 42, "cpa_target": 26, "seasonality": "Pic Oct–Mars"},
            "NL": {"volume": 5400, "cpc": 1.25, "kd": 38, "cpa_target": 30, "seasonality": "Pic Oct–Mars (top)"},
        },
    },
    {
        "slug": "siege-douche-ergonomique",
        "rank": 20,
        "emoji": "🚿",
        "name": "Siège de douche ergonomique",
        "category": "Salle de bain",
        "tagline": "La douche devient un moment de repos. Pliage mural, aucun encombrement.",
        "description": "Tabouret de douche pliable, antidérapant, pieds ventouses sécurité, pliage mural.",
        "keywords": ["siège douche", "duschhocker", "shower stool"],
        "buy_price_eur": [18, 26],
        "sell_price_eur": [59, 89],
        "aov_eur": [59, 89],
        "margin_pct": 76,
        "ecf_score": 83,
        "best_country": "FR",
        "hero": False,
        "suppliers": ["CJ Dropshipping", "BigBuy", "AliExpress"],
        "country_metrics": {
            "FR": {"volume": 14800, "cpc": 1.10, "kd": 42, "cpa_target": 28, "seasonality": "Stable"},
            "DE": {"volume": 22200, "cpc": 1.40, "kd": 50, "cpa_target": 32, "seasonality": "Stable"},
            "CH": {"volume": 1000,  "cpc": 1.55, "kd": 38, "cpa_target": 35, "seasonality": "Stable"},
            "BE": {"volume": 1600,  "cpc": 1.20, "kd": 36, "cpa_target": 28, "seasonality": "Stable"},
            "UK": {"volume": 12100, "cpc": 0.95, "kd": 44, "cpa_target": 25, "seasonality": "Stable"},
            "NL": {"volume": 2900,  "cpc": 1.15, "kd": 38, "cpa_target": 28, "seasonality": "Stable"},
        },
    },
]


def enrich(niche: dict) -> dict:
    """Ajoute total_volume et un résumé pré-calculé pour l'API."""
    total_volume = sum(m["volume"] for m in niche["country_metrics"].values())
    avg_cpc = round(sum(m["cpc"] for m in niche["country_metrics"].values()) / 6, 2)
    avg_kd = round(sum(m["kd"] for m in niche["country_metrics"].values()) / 6, 1)
    return {
        **niche,
        "total_volume_monthly": total_volume,
        "avg_cpc_eur": avg_cpc,
        "avg_kd": avg_kd,
    }


async def seed_niches(db) -> int:
    """Idempotent: upsert the 20 niches in the `niches` collection."""
    now = datetime.now(timezone.utc).isoformat()
    count = 0
    for n in NICHES:
        doc = enrich(n)
        await db.niches.update_one(
            {"slug": doc["slug"]},
            {
                "$set": {**doc, "updated_at": now},
                "$setOnInsert": {"created_at": now},
            },
            upsert=True,
        )
        count += 1
    # Upsert countries reference
    for c in COUNTRIES:
        await db.countries.update_one(
            {"code": c["code"]},
            {"$set": c},
            upsert=True,
        )
    return count
